/**
 * Newsletter campaigns (C-111).
 *
 * ## What this is NOT
 *
 * It is not an ESP. There is no bounce handling, no complaint feedback loop, no
 * suppression list and no reputation management. Sending a campaign to a large
 * list through a shop's own SMTP relay can cost that shop the deliverability of
 * its ORDER CONFIRMATIONS, which is a far more expensive thing to lose than a
 * newsletter — so the admin screen says exactly that, and the batch size is
 * small on purpose.
 *
 * ## List-Unsubscribe is the load-bearing part
 *
 * It is the one header that decides whether a mailing list is treated as a
 * mailing list or as a person sending a lot of mail. Gmail and Outlook both put
 * a one-click Unsubscribe control on a message that carries it, and route a
 * message WITHOUT one toward the spam-complaint button instead — and a
 * complaint costs the sending domain, which is the shop's.
 *
 * `List-Unsubscribe-Post: List-Unsubscribe=One-Click` is what makes that
 * control work without the reader leaving their inbox. Both are set here, from
 * the token `newsletter-confirm.ts` already mints, so the link in the footer
 * and the header point at the same endpoint with the same proof.
 *
 * ## Resumable by construction
 *
 * A campaign is sent in batches by the existing scheduler tick, with a cursor
 * on the record. A process restart mid-send resumes rather than starting again
 * — sending a newsletter twice is the failure people actually remember.
 */
import { unsubscribeUrl } from './newsletter-confirm';
import type { EmailMessage } from './email';
import { escapeHtml } from './escape-html';

/** The collection campaigns live in — an ordinary custom entity, so all three drivers work. */
export const CAMPAIGN_TYPE = 'newsletter_campaign';

/** Per scheduler tick. Deliberately small — see the deliverability note above. */
export const CAMPAIGN_BATCH_SIZE = 25;

export type CampaignStatus = 'draft' | 'sending' | 'sent' | 'failed';

export interface Campaign {
  subject: string;
  body: string;
  status: CampaignStatus;
  /** How many addresses have been attempted, and the resume point. */
  cursor?: number;
  sent_count?: number;
  failed_count?: number;
}

/**
 * The next slice of the list to attempt.
 *
 * Pure, and it takes the cursor rather than "everyone who has not been sent to"
 * — the alternative needs a per-recipient record, which is a second collection
 * to keep consistent for a gain nobody can see.
 */
export function nextBatch<T>(
  subscribers: readonly T[],
  cursor: number,
  size: number = CAMPAIGN_BATCH_SIZE,
): T[] {
  const from = Math.max(0, Math.floor(cursor) || 0);
  return subscribers.slice(from, from + Math.max(1, size));
}

/**
 * Turn a campaign and one address into a message.
 *
 * The plain-text part is the source of truth and the HTML is derived from it:
 * an operator writing a newsletter in a textarea should not have to write it
 * twice, and a text part generated by stripping HTML is the one that ends up
 * unreadable.
 */
export function campaignMessage(
  campaign: Pick<Campaign, 'subject' | 'body'>,
  email: string,
  origin: string,
): EmailMessage {
  const unsub = unsubscribeUrl(origin, email);
  const text = `${campaign.body}\n\n—\nTo stop receiving these: ${unsub}`;

  const paragraphs = campaign.body
    .split(/\n{2,}/)
    .map((p) => `<p>${escapeHtml(p).replace(/\n/g, '<br />')}</p>`)
    .join('\n');

  const html = `${paragraphs}\n<hr />\n`
    + `<p style="font-size:12px;color:#6b7280">`
    + `<a href="${escapeHtml(unsub)}">Unsubscribe</a>`
    + `</p>`;

  return {
    to: email,
    subject: campaign.subject,
    text,
    html,
    // What makes sendEmail refuse it on an EMAIL_CAMPAIGNS=0 install:
    // the message itself says it is list mail, so no future sender of bulk mail
    // can forget to ask.
    category: 'bulk',
    headers: {
      // Both forms: a mail client that cannot POST falls back to the mailto,
      // and one that can gives the reader a one-click control.
      'List-Unsubscribe': `<${unsub}>`,
      'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
    },
  };
}

/** Is this campaign finished? */
export function campaignComplete(campaign: Campaign, total: number): boolean {
  return (campaign.cursor ?? 0) >= total;
}

/**
 * Why a campaign cannot be sent, or null.
 *
 * Checked before anything is queued, so an operator finds out at the moment
 * they press Send rather than from a half-delivered list.
 */
export function campaignProblem(
  campaign: Pick<Campaign, 'subject' | 'body'>,
  subscriberCount: number,
  emailChannelReady: boolean,
  /** False when the install has EMAIL_CAMPAIGNS=0. */
  bulkAllowed = true,
): string | null {
  if (!campaign.subject?.trim()) return 'A campaign needs a subject.';
  if (!campaign.body?.trim()) return 'A campaign needs something to say.';
  if (campaign.subject.length > 200) return 'That subject is too long for a mail client to show.';
  if (subscriberCount === 0) return 'Nobody has confirmed a subscription yet.';
  if (!emailChannelReady) {
    return 'No email channel is configured, so nothing could be delivered. '
      + 'Set one up first — a campaign marked "sent" that went nowhere is worse than an error.';
  }
  if (!bulkAllowed) {
    // Said at Send, not discovered from a list where every address "failed":
    // the mailbox is licensed for one-to-one mail, and a newsletter through it
    // breaks its terms and burns through its per-minute allowance.
    return 'Newsletter campaigns are switched off for this site\'s mail channel (EMAIL_CAMPAIGNS=0): '
      + 'it is licensed for one-to-one mail only. Send campaigns through a service that allows bulk mail.';
  }
  return null;
}
