/**
 * Tiny declarative validator. Returns either `{ ok: true, value }` or
 * `{ ok: false, errors }`. No dependency on zod — keep the bundle small.
 */
import { transliterate } from './text-search';
/**
 * Input hardening rules shared by every field type.
 *
 * The principle: a field accepts the type it declares and NOTHING adjacent.
 * JavaScript's coercions make "adjacent" surprisingly wide — `Number(true)` is
 * 1, `Number([7])` is 7, `Number('0x10')` is 16 — so a `number` field that
 * coerces will happily take a boolean, a one-element array, or a hex string.
 * None of those are things an honest client sends, and each is a way to put a
 * value into the system that the author of the schema did not picture.
 */

/** Longest a string field may be when its rule names no explicit max. */
export const DEFAULT_STRING_MAX = 20_000;

/**
 * Characters no legitimate input contains.
 *
 * A NUL truncates strings in C-backed libraries (SQLite, libvips, anything
 * shelling out), so `evil\u0000.jpg` can pass a `.jpg` check and then be
 * written as `evil`. The other C0 controls have no meaning in user text.
 * Tab/newline/carriage-return are excluded from the ban — they are legitimate
 * in prose fields.
 */
const FORBIDDEN_CONTROLS = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/;

/**
 * A string that is genuinely a number. Deliberately narrow: no hex, no
 * exponent, no surrounding whitespace, no `Infinity`. A real JSON number
 * arrives already parsed, so nothing legitimate is lost.
 */
const NUMERIC_STRING = /^-?(?:\d+(?:\.\d+)?|\.\d+)$/;

/** Ids are generated by us: UUIDs, kebab slugs, or short numerics. */
const ID_CHARSET = /^[A-Za-z0-9_-]{1,64}$/;
const SLUG_CHARSET = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
/**
 * The most items ONE repeater field may hold, whatever its definition says.
 *
 * The definition's own `max` is the operator's editorial limit; this is the
 * server's. Without it the only ceiling is the 2 MB request body cap in the
 * middleware, and ten thousand one-field items fit inside that comfortably —
 * each one costing a nested validate() call.
 */
export const MAX_REPEATER_ITEMS = 200;
/**
 * Deliberately the same shape used at every other door in this codebase
 * (contact, newsletter, the WooCommerce planner): one @, something either
 * side, a dot in the domain. Not RFC 5322 — nothing here is, on purpose. A
 * regex that accepts every legal address accepts a great many illegal ones,
 * and the only real test of an address is sending to it.
 */
const EMAIL_SHAPE = /^[^\s@]+@[^\s@.]+\.[^\s@]+$/;
/** ISO date, or ISO date-time. Anything else is somebody's local format. */
const ISO_DATE = /^\d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}(?::\d{2})?(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?)?$/;

export type FieldRule =
  | { type: 'string'; min?: number; max?: number; pattern?: RegExp; optional?: boolean }
  | { type: 'enum'; values: readonly string[]; optional?: boolean }
  | { type: 'number'; min?: number; max?: number; int?: boolean; optional?: boolean }
  | { type: 'boolean'; optional?: boolean }
  | { type: 'array'; of: 'string' | 'number'; max?: number; optional?: boolean }
  | { type: 'id'; optional?: boolean } // non-empty string
  | { type: 'slug'; optional?: boolean }
  | { type: 'email'; optional?: boolean }
  | { type: 'url'; optional?: boolean }
  | { type: 'date'; optional?: boolean }
  /**
   * A reference to a record in another collection.
   *
   * The VALUE is validated here (it has to look like an id); whether the thing
   * it points at exists is checked by the write path, which is the only layer
   * with a database. Keeping that split means this stays pure and testable.
   */
  | { type: 'ref'; to: string; optional?: boolean }
  /** A media-library id. Resolved to a URL on read; stored as the id. */
  | { type: 'media'; optional?: boolean }
  /**
   * A file a STRANGER uploaded through a public form (C-23).
   *
   * Separate from `media` because the bytes live somewhere else and are read
   * differently: a media id points into the public library, and this points at
   * a file only an authenticated route can serve. Making them one kind would
   * mean one of the two read policies silently applied to the other, and the
   * direction that goes wrong publishes a CV.
   */
  | { type: 'file'; optional?: boolean }
  /**
   * A REPEATER: an ordered list of items, each item a small record (C-123).
   *
   * `fields` gives every item the same shape. `layouts` instead gives each item
   * a CHOICE of named shapes, tagged with `_layout` — which is ACF's "flexible
   * content" (C-126) expressed as one rule rather than a second feature.
   *
   * ONE level. A repeater may not contain a repeater, and the definition
   * validators refuse it — which removes the recursion-depth question, the
   * cycle question, and the "how deep does the GDPR sweep walk" question all
   * at once.
   */
  | {
      type: 'repeater';
      fields?: { name: string; rule: FieldRule }[];
      layouts?: { name: string; label: string; fields: { name: string; rule: FieldRule }[] }[];
      min?: number;
      max?: number;
      optional?: boolean;
    };

export type Schema = Record<string, FieldRule>;

export interface ValidateOk<T> {
  ok: true;
  value: T;
}
export interface ValidateErr {
  ok: false;
  errors: Record<string, string>;
}

export function validate<T = Record<string, unknown>>(
  input: unknown,
  schema: Schema,
): ValidateOk<T> | ValidateErr {
  if (!input || typeof input !== 'object' || Array.isArray(input)) {
    return { ok: false, errors: { _: 'Body must be a JSON object' } };
  }
  const errors: Record<string, string> = {};
  // A null-prototype bag: assigning value['__proto__'] to a plain {} invokes
  // the inherited setter and REPARENTS the object instead of storing a field,
  // so a field literally named __proto__ silently vanished — the exact
  // accept-and-discard shape the default-case fix was meant to end. With no
  // prototype there is no setter to hit and no inherited member to read.
  const value: Record<string, unknown> = Object.create(null);
  const src = input as Record<string, unknown>;

  for (const [key, rule] of Object.entries(schema)) {
    // OWN properties only. `src[key]` on a JSON.parse'd body returns the
    // inherited Object.prototype member for a field named `constructor` or
    // `toString`, which read as "present" and defeated the absent-check below.
    const v = Object.prototype.hasOwnProperty.call(src, key) ? src[key] : undefined;
    if (v === undefined || v === null || v === '') {
      if (!('optional' in rule) || !rule.optional) {
        errors[key] = `${key} is required`;
      }
      continue;
    }
    switch (rule.type) {
      case 'string': {
        if (typeof v !== 'string') {
          errors[key] = `${key} must be a string`;
          break;
        }
        if (FORBIDDEN_CONTROLS.test(v)) {
          errors[key] = `${key} contains control characters`;
          break;
        }
        if (rule.min !== undefined && v.length < rule.min) {
          errors[key] = `${key} must be at least ${rule.min} chars`;
          break;
        }
        // A rule that names no max still gets one. Unbounded strings are
        // bounded only by the request-body ceiling, which is far larger than
        // any single field should be.
        const strMax = rule.max ?? DEFAULT_STRING_MAX;
        if (v.length > strMax) {
          errors[key] = `${key} must be at most ${strMax} chars`;
          break;
        }
        if (rule.pattern && !rule.pattern.test(v)) {
          errors[key] = `${key} has invalid format`;
          break;
        }
        value[key] = v;
        break;
      }
      case 'enum': {
        if (typeof v !== 'string' || !rule.values.includes(v)) {
          errors[key] = `${key} must be one of: ${rule.values.join(', ')}`;
          break;
        }
        value[key] = v;
        break;
      }
      case 'number': {
        // Strict. `Number()` would accept true (1), [] (0), [7] (7), '0x10'
        // (16) and ' 7 ' (7) — none of which an honest client sends, and each
        // of which puts an unexpected value where a number was declared.
        let n: number;
        if (typeof v === 'number') {
          n = v;
        } else if (typeof v === 'string' && NUMERIC_STRING.test(v)) {
          n = Number(v);
        } else {
          errors[key] = `${key} must be a number`;
          break;
        }
        if (!Number.isFinite(n)) {
          errors[key] = `${key} must be a number`;
          break;
        }
        if (rule.int && !Number.isInteger(n)) {
          errors[key] = `${key} must be an integer`;
          break;
        }
        if (rule.min !== undefined && n < rule.min) {
          errors[key] = `${key} must be >= ${rule.min}`;
          break;
        }
        if (rule.max !== undefined && n > rule.max) {
          errors[key] = `${key} must be <= ${rule.max}`;
          break;
        }
        value[key] = n;
        break;
      }
      case 'boolean': {
        if (typeof v !== 'boolean') {
          errors[key] = `${key} must be true or false`;
          break;
        }
        value[key] = v;
        break;
      }
      case 'array': {
        if (!Array.isArray(v)) {
          errors[key] = `${key} must be an array`;
          break;
        }
        if (rule.max !== undefined && v.length > rule.max) {
          errors[key] = `${key} may have at most ${rule.max} items`;
          break;
        }
        const wrong = v.findIndex(item => typeof item !== rule.of);
        if (wrong >= 0) {
          errors[key] = `${key}[${wrong}] must be a ${rule.of}`;
          break;
        }
        if (rule.of === 'string') {
          // A 20-item cap on an array of 1 MB strings is not a cap.
          const bad = (v as string[]).findIndex(
            item => item.length > DEFAULT_STRING_MAX || FORBIDDEN_CONTROLS.test(item),
          );
          if (bad >= 0) {
            errors[key] = `${key}[${bad}] is too long or contains control characters`;
            break;
          }
        } else if (rule.of === 'number') {
          const bad = (v as number[]).findIndex(item => !Number.isFinite(item));
          if (bad >= 0) {
            errors[key] = `${key}[${bad}] must be a finite number`;
            break;
          }
        }
        value[key] = v;
        break;
      }
      case 'id':
      // A ref and a media handle ARE ids — the same charset, for the same
      // reason. What makes them different is what the write path does with
      // them afterwards (look the record up, resolve the URL), not what counts
      // as a valid value here.
      case 'ref':
      case 'media': {
        // Ids are values WE generate: UUIDs, kebab slugs, short numerics. A
        // free-form 64-char string here let `../../etc/passwd`, `<script>` and
        // embedded NULs through into lookups, logs and URLs.
        if (typeof v !== 'string' || !ID_CHARSET.test(v)) {
          errors[key] = `${key} must be an id (letters, digits, dash, underscore; 1-64 chars)`;
          break;
        }
        value[key] = v;
        break;
      }
      case 'repeater': {
        if (!Array.isArray(v)) {
          errors[key] = `${key} must be a list`;
          break;
        }
        if (v.length > MAX_REPEATER_ITEMS) {
          // A hard ceiling regardless of what the definition asks for. The only
          // other limit on the way in is the 2 MB body cap in the middleware,
          // which is not an item cap — ten thousand one-field items fit inside
          // it comfortably, and each one costs a nested validate().
          errors[key] = `${key} may have at most ${MAX_REPEATER_ITEMS} items`;
          break;
        }
        if (rule.max !== undefined && v.length > rule.max) {
          errors[key] = `${key} may have at most ${rule.max} items`;
          break;
        }
        if (rule.min !== undefined && v.length < rule.min) {
          errors[key] = `${key} needs at least ${rule.min} items`;
          break;
        }

        const items: Record<string, unknown>[] = [];
        let failed = false;
        for (let i = 0; i < v.length; i += 1) {
          const raw = v[i];
          if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
            errors[`${key}[${i}]`] = `${key}[${i}] must be an object`;
            failed = true;
            continue;
          }
          const item = raw as Record<string, unknown>;

          // Which shape does THIS item have? One for a plain repeater; the one
          // its `_layout` names for a flexible-content repeater.
          let sub: { name: string; rule: FieldRule }[] | undefined;
          let layout: string | undefined;
          if (rule.layouts && rule.layouts.length > 0) {
            layout = typeof item._layout === 'string' ? item._layout : '';
            const found = rule.layouts.find((l) => l.name === layout);
            if (!found) {
              // Naming no layout and naming an unknown one are the same
              // mistake: there is no shape to check the item against, and
              // guessing one would store fields nobody declared.
              errors[`${key}[${i}]`] = `${key}[${i}] must name one of: ${rule.layouts.map((l) => l.name).join(', ')}`;
              failed = true;
              continue;
            }
            sub = found.fields;
          } else {
            sub = rule.fields ?? [];
          }

          const schema: Schema = {};
          for (const f of sub) schema[f.name] = f.rule;
          const { _layout, ...values } = item;
          const res = validate<Record<string, unknown>>(values, schema);
          if (!res.ok) {
            // Re-keyed as `field[3].child`, so an operator is told which item
            // and which box rather than "invalid".
            for (const [k, msg] of Object.entries(res.errors)) {
              errors[`${key}[${i}].${k}`] = `${key}[${i}].${msg}`;
            }
            failed = true;
            continue;
          }
          items.push(layout ? { _layout: layout, ...res.value } : res.value);
        }
        if (failed) break;
        value[key] = items;
        break;
      }
      // NOTE: placed here, not next to `case 'id'`. That label deliberately
      // FALLS THROUGH into `ref`/`media`, so a case inserted between them
      // silently re-routes every `id` field — which is exactly what happened,
      // and what tests/field-kinds.test.mjs caught within a minute.
      case 'file': {
        // The id SHAPE is checked here; whether the file exists is checked by
        // the write path, the only layer with a filesystem — the same split
        // `ref` and `media` follow.
        if (typeof v !== 'string' || !/^pf_[0-9a-f]{20}$/.test(v)) {
          errors[key] = `${key} must be an uploaded file reference`;
          break;
        }
        value[key] = v;
        break;
      }
      case 'slug': {
        if (typeof v !== 'string' || v.length > 200 || !SLUG_CHARSET.test(v)) {
          errors[key] = `${key} must be a slug (lowercase letters, digits and single dashes)`;
          break;
        }
        value[key] = v;
        break;
      }
      case 'email': {
        if (typeof v !== 'string' || v.length > 200 || FORBIDDEN_CONTROLS.test(v) || !EMAIL_SHAPE.test(v)) {
          errors[key] = `${key} must be an email address`;
          break;
        }
        value[key] = v;
        break;
      }
      case 'url': {
        // http and https ONLY. These values are rendered as links, and the
        // whole family this excludes — javascript:, data:, vbscript:, file: —
        // exists to be rendered as a link by somebody who did not check.
        if (typeof v !== 'string' || v.length > 2000 || FORBIDDEN_CONTROLS.test(v)) {
          errors[key] = `${key} must be a URL`;
          break;
        }
        let parsed: URL;
        try {
          parsed = new URL(v);
        } catch {
          errors[key] = `${key} must be a full URL, including https://`;
          break;
        }
        if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
          errors[key] = `${key} must be an http or https URL`;
          break;
        }
        value[key] = v;
        break;
      }
      case 'date': {
        // The shape, then that the day actually EXISTS. `new Date()` is not
        // enough on its own: it rolls 2024-02-31 forward to 2 March rather
        // than refusing it, so a form where somebody typed 31 February would
        // store a date nobody meant and every reader would disagree about
        // what it said. The round-trip catches it.
        if (typeof v !== 'string' || !ISO_DATE.test(v)) {
          errors[key] = `${key} must be a date (YYYY-MM-DD)`;
          break;
        }
        const parsed = new Date(v.length === 10 ? `${v}T00:00:00Z` : v);
        if (Number.isNaN(parsed.getTime())) {
          errors[key] = `${key} must be a real date (YYYY-MM-DD)`;
          break;
        }
        // The calendar day must EXIST. V8 rejects an impossible day in the
        // date-only form (2024-02-31 → Invalid) but silently rolls it forward
        // in a timestamp (2024-02-31T12:00Z → 2 March), so the round-trip has
        // to run for both. It compares against the day AS WRITTEN — parsed in
        // its own offset, not UTC — so a legitimate timestamp whose UTC day
        // differs (2024-03-05T23:30-05:00 is the 6th in UTC) is not rejected.
        const dateMatch = v.match(/^(\d{4})-(\d{2})-(\d{2})/);
        if (dateMatch) {
          const [, y, m, d] = dateMatch;
          // A Date built from just the date part, in UTC, must round-trip the
          // written Y-M-D. This catches 2024-02-31 regardless of any time or
          // offset that follows, because the impossible DAY is offset-agnostic.
          const dayOnly = new Date(`${y}-${m}-${d}T00:00:00Z`);
          if (Number.isNaN(dayOnly.getTime())
            || dayOnly.getUTCFullYear() !== Number(y)
            || dayOnly.getUTCMonth() + 1 !== Number(m)
            || dayOnly.getUTCDate() !== Number(d)) {
            errors[key] = `${key} must be a real date (YYYY-MM-DD)`;
            break;
          }
        }
        value[key] = v;
        break;
      }
      default: {
        /**
         * A rule type nothing here recognises.
         *
         * This branch exists because of what its absence did. The switch had
         * no default, so a field whose rule type had no `case` fell straight
         * through: no error raised, and `value[key]` never assigned. The
         * result was `{ ok: true, value: {} }` — the field ACCEPTED and
         * SILENTLY DISCARDED. Four of the ten field types the admin builder
         * offers (slug, email, url, date) were in exactly that state, so
         * anyone who built a content type with an email field filled it in,
         * saw it save, and found it empty afterwards.
         *
         * Failing closed here means the next field type added to a definition
         * without a case is a visible error on one record instead of a silent
         * hole in every record.
         */
        errors[key] = `${key} has a field type this server does not understand`;
        break;
      }
    }
  }
  if (Object.keys(errors).length > 0) return { ok: false, errors };
  return { ok: true, value: value as T };
}

/**
 * Stable non-cryptographic hash (FNV-1a), for the slug fallback below.
 *
 * Deterministic is the requirement: the same name must always produce the same
 * slug, or the uniqueness check compares against a moving target. Nothing here
 * is security-relevant, so a real digest would only add an import.
 */
export function stableHash(input: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(36);
}

/**
 * URL slug from arbitrary human text.
 *
 * Non-Latin scripts are TRANSLITERATED, not discarded. The previous version
 * kept only `[a-z0-9]`, so an all-Greek name — "αλυσίδα ατσάλι" — produced an
 * empty string. That was not a cosmetic problem: an empty slug skipped the
 * product uniqueness check (`if (slug && …)`), so every Greek product created
 * without a manual slug collided on `''` and became unreachable by slug.
 *
 * The result is therefore guaranteed non-empty. A name that transliterates to
 * nothing at all (emoji, CJK, symbols) falls back to a hash of the input rather
 * than to `''` — ugly, but addressable and unique, which `''` is not.
 */
export function slugify(input: string): string {
  const slug = transliterate(input)
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80)
    // A trailing dash can survive the 80-char truncation above.
    .replace(/-+$/g, '');
  return slug || `item-${stableHash(input)}`;
}

/**
 * Parse a paging parameter from a query string.
 *
 * `Number()` on a query value is the same trap as on a body field: `?limit=abc`
 * yields NaN, and `slice(0, NaN)` returns an empty list — so a typo looks
 * exactly like "no results" to whoever is debugging it. `?limit=0x10` yields 16
 * for no reason anyone intended.
 *
 * Junk falls back to the default rather than erroring: a list endpoint should
 * still list. Out-of-range values clamp.
 */
export function parsePaging(
  raw: string | null | undefined,
  { fallback, min, max }: { fallback: number; min: number; max: number },
): number {
  if (raw === null || raw === undefined || raw.trim() === '') return fallback;
  if (!NUMERIC_STRING.test(raw.trim())) return fallback;
  const n = Math.floor(Number(raw.trim()));
  if (!Number.isFinite(n)) return fallback;
  return Math.min(Math.max(n, min), max);
}
