#!/usr/bin/env node
/**
 * Newsletter campaigns (C-111).
 *
 * The load-bearing part is not the composer. It is `List-Unsubscribe`: the one
 * header that decides whether a mailing list is treated as a mailing list or as
 * a person sending a lot of mail. Gmail and Outlook put a one-click Unsubscribe
 * control on a message that carries it, and route a message WITHOUT one toward
 * the spam-complaint button — and a complaint costs the sending domain, which
 * on these installs is the same domain the ORDER CONFIRMATIONS go out from.
 *
 * Run with:  node tests/newsletter-campaign.test.mjs
 */
import { loadTs } from './lib/load.mjs';

const C = await loadTs('src/lib/newsletter-campaign.ts');
const M = await loadTs('src/lib/email-mime.ts');

let passed = 0;
const failures = [];
function check(name, fn) {
  try { fn(); passed += 1; }
  catch (err) { failures.push(`${name}: ${err.message}`); }
}
function eq(a, b, what = '') {
  if (JSON.stringify(a) !== JSON.stringify(b)) {
    throw new Error(`${what} expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`);
  }
}

const CAMPAIGN = { subject: 'Spring frames', body: 'New arrivals.\n\nCome and look.' };
const ORIGIN = 'https://shop.example.gr';

// ────────────────────────────────────────────── the header that matters

check('THE HEADER: every message carries List-Unsubscribe', () => {
  const msg = C.campaignMessage(CAMPAIGN, 'anna@example.gr', ORIGIN);
  if (!msg.headers?.['List-Unsubscribe']) throw new Error(JSON.stringify(msg.headers));
  if (!/^<https:\/\/shop\.example\.gr\/api\/newsletter\/unsubscribe\?token=/.test(msg.headers['List-Unsubscribe'])) {
    throw new Error(msg.headers['List-Unsubscribe']);
  }
});

check('...and the one-click companion, which is what makes it a BUTTON', () => {
  const msg = C.campaignMessage(CAMPAIGN, 'anna@example.gr', ORIGIN);
  eq(msg.headers['List-Unsubscribe-Post'], 'List-Unsubscribe=One-Click');
});

check('the header and the footer link point at the SAME token', () => {
  // Two tokens would mean the header could work while the visible link did not,
  // or the reverse, and nobody would notice until somebody complained.
  const msg = C.campaignMessage(CAMPAIGN, 'anna@example.gr', ORIGIN);
  const fromHeader = msg.headers['List-Unsubscribe'].replace(/^<|>$/g, '');
  if (!msg.text.includes(fromHeader)) throw new Error('the text footer differs');
  if (!msg.html.includes(fromHeader)) throw new Error('the html footer differs');
});

check('two subscribers get two DIFFERENT tokens', () => {
  const a = C.campaignMessage(CAMPAIGN, 'a@example.gr', ORIGIN).headers['List-Unsubscribe'];
  const b = C.campaignMessage(CAMPAIGN, 'b@example.gr', ORIGIN).headers['List-Unsubscribe'];
  if (a === b) throw new Error('one token would unsubscribe the wrong person');
});

// ─────────────────────────────────────────────────────── the message

check('the TEXT part is the source and the HTML is derived', () => {
  // An operator writing in a textarea should not have to write it twice, and a
  // text part generated by stripping HTML is the one that ends up unreadable.
  const msg = C.campaignMessage(CAMPAIGN, 'a@example.gr', ORIGIN);
  if (!msg.text.startsWith('New arrivals.')) throw new Error(msg.text);
  if (!msg.html.includes('<p>New arrivals.</p>')) throw new Error(msg.html);
  if (!msg.html.includes('<p>Come and look.</p>')) throw new Error('paragraphs not split');
});

check('a body containing markup is ESCAPED, not rendered', () => {
  // The body is operator text, but an operator pasting from a web page should
  // not be able to send a message with somebody else's script in it.
  const msg = C.campaignMessage({ subject: 'x', body: '<script>alert(1)</script>' }, 'a@x.gr', ORIGIN);
  if (msg.html.includes('<script')) throw new Error(msg.html);
  if (!msg.html.includes('&lt;script&gt;')) throw new Error(msg.html);
});

// ────────────────────────────────────────────────── header injection

check('A CRLF IN A HEADER VALUE CANNOT SPLIT THE MESSAGE', () => {
  // The whole reason header values are sanitised where they are written rather
  // than by each caller.
  //
  // The property is that no NEW HEADER LINE appears — not that the text "Bcc:"
  // is absent. `headerSafe` flattens the CRLF to a space, so the injected text
  // survives as part of the X-Test VALUE, which is harmless: a header is what
  // starts a line. The first version of this test asserted the wrong thing and
  // failed on correct code.
  const mime = M.buildMimeMessage({
    from: 'shop@example.gr', to: 'a@example.gr', subject: 'Hi', text: 'body',
    headers: { 'X-Test': 'ok\r\nBcc: victim@example.gr' },
  });
  if (/\r\nBcc:/i.test(mime)) throw new Error('a header line was injected');
  if (/^Bcc:/im.test(mime)) throw new Error('a header line was injected');
  // ...and it did survive, flattened, on the line it belongs to.
  if (!/X-Test: ok Bcc: victim@example\.gr/.test(mime)) throw new Error(mime.slice(0, 400));
});

check('a header value cannot inject a BODY either', () => {
  // A blank line ends the headers, so one in a value would make everything
  // after it the message body.
  //
  // The property is that there is EXACTLY ONE header/body separator and the
  // body is still ours. The injected text survives, flattened, as part of the
  // X-Test value — which is exactly as harmless as it sounds, and asserting its
  // absence (as this test first did) fails on correct code.
  const mime = M.buildMimeMessage({
    from: 'a@b.gr', to: 'c@d.gr', subject: 'x', text: 'real body',
    headers: { 'X-Test': 'v\r\n\r\nforged body' },
  });
  const parts = mime.split('\r\n\r\n');
  eq(parts.length, 2, 'exactly one header/body separator');
  eq(parts[1], Buffer.from('real body').toString('base64'), 'the body is still ours');
  if (!/^X-Test: v forged body$/m.test(parts[0])) throw new Error(parts[0]);
});

check('a header cannot overwrite the message identity', () => {
  // From, To, Subject and the content type are what the message IS. A caller
  // replacing one is a caller forging a message.
  const mime = M.buildMimeMessage({
    from: 'shop@example.gr', to: 'a@example.gr', subject: 'Real', text: 'body',
    headers: { From: 'bank@example.com', Subject: 'Fake', 'Content-Type': 'text/html' },
  });
  if (mime.includes('bank@example.com')) throw new Error('From was overwritten');
  if (mime.includes('Subject: Fake')) throw new Error('Subject was overwritten');
  if (!mime.includes('Subject: Real')) throw new Error('the real subject is gone');
});

check('a header with an illegal NAME is dropped', () => {
  const mime = M.buildMimeMessage({
    from: 'a@b.gr', to: 'c@d.gr', subject: 'x', text: 'y',
    headers: { 'Not A Header': 'v', 'X-Fine': 'v' },
  });
  if (mime.includes('Not A Header')) throw new Error(mime);
  if (!mime.includes('X-Fine: v')) throw new Error('a legal header was dropped');
});

check('no headers at all is unchanged', () => {
  const withNone = M.buildMimeMessage({ from: 'a@b.gr', to: 'c@d.gr', subject: 'x', text: 'y' });
  const withEmpty = M.buildMimeMessage({ from: 'a@b.gr', to: 'c@d.gr', subject: 'x', text: 'y', headers: {} });
  eq(withNone, withEmpty);
});

// ────────────────────────────────────────────────────────── batching

check('a batch resumes from the cursor', () => {
  const subs = Array.from({ length: 10 }, (_, i) => ({ email: `a${i}@x.gr` }));
  eq(C.nextBatch(subs, 0, 4).map((s) => s.email), ['a0@x.gr', 'a1@x.gr', 'a2@x.gr', 'a3@x.gr']);
  eq(C.nextBatch(subs, 8, 4).map((s) => s.email), ['a8@x.gr', 'a9@x.gr']);
  eq(C.nextBatch(subs, 10, 4), []);
});

check('a nonsense cursor does not resend the whole list', () => {
  const subs = [{ email: 'a@x.gr' }];
  eq(C.nextBatch(subs, -5, 4).length, 1);
  eq(C.nextBatch(subs, NaN, 4).length, 1);
});

check('completion is decided by the cursor, not by a count', () => {
  eq(C.campaignComplete({ cursor: 10 }, 10), true);
  eq(C.campaignComplete({ cursor: 9 }, 10), false);
  eq(C.campaignComplete({}, 0), true);
});

// ──────────────────────────────────────────── refusing before sending

check('a campaign with no way to be DELIVERED is refused', () => {
  // "Sent" on a campaign that went nowhere is worse than an error: the
  // operator has no reason to look again.
  const msg = C.campaignProblem(CAMPAIGN, 5, false);
  if (!msg) throw new Error('accepted a campaign with no email channel');
  if (!/email channel/i.test(msg)) throw new Error(msg);
});

check('a campaign to nobody is refused', () => {
  if (!C.campaignProblem(CAMPAIGN, 0, true)) throw new Error('accepted an empty list');
});

check('an empty subject or body is refused', () => {
  if (!C.campaignProblem({ subject: '', body: 'x' }, 5, true)) throw new Error('no subject');
  if (!C.campaignProblem({ subject: 'x', body: '  ' }, 5, true)) throw new Error('no body');
});

check('a complete campaign is accepted', () => {
  eq(C.campaignProblem(CAMPAIGN, 5, true), null);
});

// A campaign message SAYS it is list mail, so sendEmail can refuse it on a
// channel with campaigns off without every bulk sender having to remember to.
check('a campaign message is marked bulk', () => {
  eq(C.campaignMessage(CAMPAIGN, 'a@example.gr', ORIGIN).category, 'bulk');
});

check('EMAIL_CAMPAIGNS=0 refuses a campaign at Send, and says why', () => {
  const why = C.campaignProblem(CAMPAIGN, 5, true, false);
  if (!why) throw new Error('accepted a newsletter with campaigns off');
  if (!/EMAIL_CAMPAIGNS=0/.test(why)) throw new Error(`the reason does not name the setting: ${why}`);
});

check('...and the old three-argument call still accepts a complete campaign', () => {
  eq(C.campaignProblem(CAMPAIGN, 5, true), null);
});

if (failures.length) {
  console.error(`\n✗ newsletter-campaign: ${failures.length} failed, ${passed} passed\n`);
  for (const f of failures) console.error(`  · ${f}`);
  process.exit(1);
}
console.log(`✓ newsletter-campaign: ${passed} passed`);
